language: python
cache: pip

matrix:
  include:
    - python: pypy3
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.6
    - python: 3.5
    - python: 3.4
  fast_finish: true

sudo: false

install:
 - pip install -U pip
 - pip install black coverage coveralls flake8

script:
 # Unit tests
 - coverage run --source=fino ./test_fino.py -v

 # Static analysis
 - pip install pep8 pyflakes
 - flake8 --statistics --count
 - black --check --diff

after_success:
 - coveralls

after_script:
 - coverage report
