language: python

matrix:
  include:
    - python: pypy3
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.6
    - python: 3.5
    - python: 3.4
  fast_finish: true

sudo: false

install:
 - pip install coverage

script:
 - coverage run --source=fino ./test_fino.py -v

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pep8 pyflakes
 - pep8 --statistics --count *.py
 - pyflakes *.py | tee >(wc -l)

